### ISSUE TITLE
How does one sign up?

### ISSUE THREAD

**Issue by skhanker** [axfelix/pnwdc18#2]
How does one sign up?

Also, hi! Long time, no see

**Comment by eugene-barsky** [comment]
We haven't advertised it yet, but be the first one here -
https://docs.google.com/forms/d/1AnbBv9mAJyzB-Z3EMyuKFFFbNT8GL7dYE5lUFKB0NKA/edit?usp=sharing

Looking forward to seeing you there, Stephan!

E.

**Comment by skhanker** [comment]
Done!
